export interface Tool {
  slug: string;
  htmlFile: string;
  name: string;
  description: string;
  emoji: string;
  category: string;
  qCost: number;
  isNew?: boolean;
}

export const CATEGORIES = [
  { id: 'image',     emoji: '🖼️',  label: 'Image' },
  { id: 'pdf',       emoji: '📄',  label: 'PDF' },
  { id: 'text',      emoji: '📝',  label: 'Text' },
  { id: 'dev',       emoji: '⚙️',  label: 'Dev' },
  { id: 'convert',   emoji: '🔄',  label: 'Convert' },
  { id: 'privacy',   emoji: '🔒',  label: 'Privacy' },
  { id: 'media',     emoji: '🎬',  label: 'Media' },
  { id: 'utility',   emoji: '🛠️',  label: 'Utility' },
];

export const TOOLS: Tool[] = [
  // ── IMAGE ─────────────────────────────────────────────────────
  {
    slug: 'image-editor',
    htmlFile: 'image-editor.html',
    name: 'Image Editor',
    description: 'Advanced browser-based image editor - crop, resize, filters, adjustments.',
    emoji: '🖼️',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'collage',
    htmlFile: 'collage.html',
    name: 'Collage Maker',
    description: 'Create beautiful photo collages with custom layouts.',
    emoji: '🎨',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'color-picker',
    htmlFile: 'color-picker.html',
    name: 'Color Picker',
    description: 'Pick colors, convert between formats, build palettes.',
    emoji: '🎨',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'css-gradient',
    htmlFile: 'css-gradient.html',
    name: 'CSS Gradient',
    description: 'Visual CSS gradient generator with presets and live preview.',
    emoji: '🌈',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'compressor',
    htmlFile: 'compressor.html',
    name: 'Image Compressor',
    description: 'Compress images without visible quality loss.',
    emoji: '📦',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'metadata-remover',
    htmlFile: 'metadata-remover.html',
    name: 'Metadata Remover',
    description: 'View and strip EXIF metadata from photos (GPS, device info).',
    emoji: '🕵️',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'barcode-scanner',
    htmlFile: 'barcode-scanner.html',
    name: 'Barcode Scanner',
    description: 'Scan barcodes and QR codes using your camera.',
    emoji: '📷',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'screenshot-translator',
    htmlFile: 'screenshot-translator.html',
    name: 'Screenshot Translator',
    description: 'Upload a screenshot and get instant translation of text inside.',
    emoji: '🌐',
    category: 'image',
    qCost: 2,
    isNew: true,
  },
  {
    slug: 'ocr',
    htmlFile: 'ocr.html',
    name: 'OCR',
    description: 'Extract text from images using optical character recognition.',
    emoji: '🔍',
    category: 'image',
    qCost: 2,
    isNew: true,
  },
  {
    slug: 'image-to-pdf',
    htmlFile: 'image-to-pdf.html',
    name: 'Image to PDF',
    description: 'Convert one or multiple images to a PDF file.',
    emoji: '📑',
    category: 'image',
    qCost: 1,
  },

  // ── PDF ───────────────────────────────────────────────────────
  {
    slug: 'pdf-tool',
    htmlFile: 'pdf-tool.html',
    name: 'PDF Tool',
    description: 'Merge, split, rotate and compress PDF files.',
    emoji: '📄',
    category: 'pdf',
    qCost: 1,
  },
  {
    slug: 'pdf-to-word',
    htmlFile: 'pdf-to-word.html',
    name: 'PDF to Word',
    description: 'Convert PDF to editable .docx with preserved formatting.',
    emoji: '📝',
    category: 'pdf',
    qCost: 2,
  },
  {
    slug: 'pdf-reader',
    htmlFile: 'pdf-reader.html',
    name: 'PDF Reader',
    description: 'Read and annotate PDF files in your browser.',
    emoji: '📖',
    category: 'pdf',
    qCost: 1,
  },

  // ── TEXT ──────────────────────────────────────────────────────
  {
    slug: 'word-counter',
    htmlFile: 'word-counter.html',
    name: 'Word Counter',
    description: 'Count words, characters, sentences and reading time.',
    emoji: '🔢',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'markdown-editor',
    htmlFile: 'markdown-editor.html',
    name: 'Markdown Editor',
    description: 'Write Markdown with live preview and export options.',
    emoji: '✍️',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'text-diff',
    htmlFile: 'text-diff.html',
    name: 'Text Diff',
    description: 'Compare two texts and highlight differences.',
    emoji: '🔀',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'lorem-ipsum',
    htmlFile: 'lorem-ipsum.html',
    name: 'Lorem Ipsum',
    description: 'Generate placeholder text in multiple languages and formats.',
    emoji: '📃',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'readability',
    htmlFile: 'readability.html',
    name: 'Readability Checker',
    description: 'Check how readable your text is with Flesch score and suggestions.',
    emoji: '📚',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'notes',
    htmlFile: 'notes.html',
    name: 'Notes',
    description: 'Quick notes that sync across your sessions.',
    emoji: '📓',
    category: 'text',
    qCost: 0,
  },

  // ── DEV ───────────────────────────────────────────────────────
  {
    slug: 'json-formatter',
    htmlFile: 'json-formatter.html',
    name: 'JSON Formatter',
    description: 'Format, validate and minify JSON with syntax highlighting.',
    emoji: '{ }',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'regex-tester',
    htmlFile: 'regex-tester.html',
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time match highlighting.',
    emoji: '.*',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'hash-generator',
    htmlFile: 'hash-generator.html',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text or files.',
    emoji: '#️⃣',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'encode-tools',
    htmlFile: 'encode-tools.html',
    name: 'Encode Tools',
    description: 'Encode and decode Base64, URL, HTML entities and more.',
    emoji: '🔤',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'api-tester',
    htmlFile: 'api-tester.html',
    name: 'API Tester',
    description: 'Send HTTP requests and inspect responses - like a mini Postman.',
    emoji: '🔌',
    category: 'dev',
    qCost: 1,
  },
  {
    slug: 'ip-lookup',
    htmlFile: 'ip-lookup.html',
    name: 'IP & DNS Lookup',
    description: 'Look up IP info, geolocation, ISP and DNS records.',
    emoji: '🌐',
    category: 'dev',
    qCost: 0,
  },

  // ── CONVERT ───────────────────────────────────────────────────
  {
    slug: 'converter',
    htmlFile: 'converter.html',
    name: 'Unit Converter',
    description: 'Convert between units - length, weight, temperature, area and more.',
    emoji: '⚖️',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'unit-converter',
    htmlFile: 'unit-converter.html',
    name: 'Unit Converter Pro',
    description: 'Advanced unit conversion with more categories.',
    emoji: '📐',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'currency',
    htmlFile: 'currency.html',
    name: 'Currency Converter',
    description: 'Real-time currency conversion with 18+ currencies.',
    emoji: '💱',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'qr-generator',
    htmlFile: 'qr-generator.html',
    name: 'QR Generator',
    description: 'Generate QR codes for URLs, text, and WiFi credentials.',
    emoji: '⬛',
    category: 'convert',
    qCost: 0,
  },

  // ── PRIVACY ───────────────────────────────────────────────────
  {
    slug: 'password-generator',
    htmlFile: 'password-generator.html',
    name: 'Password Generator',
    description: 'Generate strong, customizable passwords instantly.',
    emoji: '🔑',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'secure-notes',
    htmlFile: 'secure-notes.html',
    name: 'Secure Notes',
    description: 'Encrypted notes that never leave your device.',
    emoji: '🔐',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'vault',
    htmlFile: 'vault.html',
    name: 'Vault',
    description: 'Encrypted local storage for sensitive data.',
    emoji: '🏦',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'file-vault',
    htmlFile: 'file-vault.html',
    name: 'File Vault',
    description: 'Encrypt and store files securely in your browser.',
    emoji: '🔒',
    category: 'privacy',
    qCost: 1,
  },
  {
    slug: 'temp-email',
    htmlFile: 'temp-email.html',
    name: 'Temp Email',
    description: 'Generate a temporary disposable email address.',
    emoji: '📧',
    category: 'privacy',
    qCost: 0,
  },

  // ── MEDIA ─────────────────────────────────────────────────────
  {
    slug: 'audio-recorder',
    htmlFile: 'audio-recorder.html',
    name: 'Audio Recorder',
    description: 'Record audio from your microphone and download as MP3/WAV.',
    emoji: '🎙️',
    category: 'media',
    qCost: 1,
  },
  {
    slug: 'screen-recorder',
    htmlFile: 'screen-recorder.html',
    name: 'Screen Recorder',
    description: 'Record your screen directly in the browser.',
    emoji: '🎬',
    category: 'media',
    qCost: 1,
  },

  // ── UTILITY ───────────────────────────────────────────────────
  {
    slug: 'pomodoro',
    htmlFile: 'pomodoro.html',
    name: 'Pomodoro Timer',
    description: 'Focus timer using the Pomodoro technique.',
    emoji: '🍅',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'world-clock',
    htmlFile: 'world-clock.html',
    name: 'World Clock',
    description: 'See current time in cities around the world.',
    emoji: '🌍',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'random',
    htmlFile: 'random.html',
    name: 'Random Generator',
    description: 'Generate random numbers, shuffle lists, flip coins.',
    emoji: '🎲',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'typing_trainer_10_fingers',
    htmlFile: 'typing_trainer_10_fingers.html',
    name: 'Typing Trainer',
    description: 'Practice touch typing with 10 fingers - improve your WPM.',
    emoji: '⌨️',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'cv-builder',
    htmlFile: 'cv-builder.html',
    name: 'CV Builder',
    description: 'Build a professional CV and export to PDF.',
    emoji: '💼',
    category: 'utility',
    qCost: 2,
  },
  {
    slug: 'diary',
    htmlFile: 'diary.html',
    name: 'Diary',
    description: 'Private diary with local encrypted storage.',
    emoji: '📔',
    category: 'utility',
    qCost: 1,
  },
  {
    slug: 'flashcards',
    htmlFile: 'flashcards.html',
    name: 'Flashcards',
    description: 'Create and study flashcard decks with spaced repetition.',
    emoji: '🃏',
    category: 'utility',
    qCost: 1,
  },
{
    slug: 'vocab-trainer',
    htmlFile: 'vocab-trainer.html',
    name: 'Vocab Trainer',
    description: 'Learn vocabulary with SM-2 spaced repetition, flip cards and multiple-choice quiz.',
    emoji: '📚',
    category: 'utility',
    qCost: 0,
    isNew: true,
  },
  {
    slug: 'word-to-pdf',
    htmlFile: 'word-to-pdf.html',
    name: 'Word to PDF',
    description: 'Convert .docx to PDF in your browser. No upload, no account.',
    emoji: '📄',
    category: 'pdf',
    qCost: 0,
  },
  {
    slug: 'file-share',
    htmlFile: 'file-share.html',
    name: 'Secure File Share',
    description: 'Share files with end-to-end encryption. Link self-destructs.',
    emoji: '🔒',
    category: 'privacy',
    qCost: 0,
    isNew: true,
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug);
}

export function getFreeTools(): Tool[] {
  return TOOLS.filter(t => t.qCost === 0);
}

export function getPaidTools(): Tool[] {
  return TOOLS.filter(t => t.qCost > 0);
}