export interface Tool {
  slug: string;
  htmlFile: string;
  name: string;
  nameVi: string;
  description: string;
  descVi: string;
  emoji: string;
  category: string;
  qCost: number;
  isNew?: boolean;
}

export const CATEGORIES = [
  { id: 'image',     emoji: '🖼️',  label: 'Image',       labelVi: 'Ảnh' },
  { id: 'pdf',       emoji: '📄',  label: 'PDF',         labelVi: 'PDF' },
  { id: 'text',      emoji: '📝',  label: 'Text',        labelVi: 'Văn bản' },
  { id: 'dev',       emoji: '⚙️',  label: 'Dev',         labelVi: 'Lập trình' },
  { id: 'convert',   emoji: '🔄',  label: 'Convert',     labelVi: 'Chuyển đổi' },
  { id: 'privacy',   emoji: '🔒',  label: 'Privacy',     labelVi: 'Bảo mật' },
  { id: 'media',     emoji: '🎬',  label: 'Media',       labelVi: 'Media' },
  { id: 'utility',   emoji: '🛠️',  label: 'Utility',     labelVi: 'Tiện ích' },
];

export const TOOLS: Tool[] = [
  // ── IMAGE ─────────────────────────────────────────────────────
  {
    slug: 'image-editor',
    htmlFile: 'image-editor.html',
    name: 'Image Editor',
    nameVi: 'Chỉnh sửa ảnh',
    description: 'Advanced browser-based image editor — crop, resize, filters, adjustments.',
    descVi: 'Chỉnh sửa ảnh nâng cao ngay trên trình duyệt — cắt, resize, bộ lọc.',
    emoji: '🖼️',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'collage',
    htmlFile: 'collage.html',
    name: 'Collage Maker',
    nameVi: 'Ghép ảnh',
    description: 'Create beautiful photo collages with custom layouts.',
    descVi: 'Tạo ảnh ghép nghệ thuật với nhiều bố cục tùy chỉnh.',
    emoji: '🎨',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'color-picker',
    htmlFile: 'color-picker.html',
    name: 'Color Picker',
    nameVi: 'Chọn màu',
    description: 'Pick colors, convert between formats, build palettes.',
    descVi: 'Chọn màu, chuyển đổi định dạng HEX/RGB/HSL, tạo bảng màu.',
    emoji: '🎨',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'css-gradient',
    htmlFile: 'css-gradient.html',
    name: 'CSS Gradient',
    nameVi: 'CSS Gradient',
    description: 'Visual CSS gradient generator with presets and live preview.',
    descVi: 'Tạo CSS gradient trực quan với bộ preset và xem trước tức thì.',
    emoji: '🌈',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'compressor',
    htmlFile: 'compressor.html',
    name: 'Image Compressor',
    nameVi: 'Nén ảnh',
    description: 'Compress images without visible quality loss.',
    descVi: 'Nén ảnh chất lượng cao, giảm dung lượng mà không mất chất lượng.',
    emoji: '📦',
    category: 'image',
    qCost: 1,
  },
  {
    slug: 'metadata-remover',
    htmlFile: 'metadata-remover.html',
    name: 'Metadata Remover',
    nameVi: 'Xóa Metadata ảnh',
    description: 'View and strip EXIF metadata from photos (GPS, device info).',
    descVi: 'Xem và xóa metadata EXIF khỏi ảnh — vị trí GPS, thiết bị, ngày chụp.',
    emoji: '🕵️',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'barcode-scanner',
    htmlFile: 'barcode-scanner.html',
    name: 'Barcode Scanner',
    nameVi: 'Quét mã vạch',
    description: 'Scan barcodes and QR codes using your camera.',
    descVi: 'Quét mã vạch và mã QR bằng camera ngay trên trình duyệt.',
    emoji: '📷',
    category: 'image',
    qCost: 0,
  },
  {
    slug: 'screenshot-translator',
    htmlFile: 'screenshot-translator.html',
    name: 'Screenshot Translator',
    nameVi: 'Dịch ảnh chụp màn hình',
    description: 'Upload a screenshot and get instant translation of text inside.',
    descVi: 'Tải ảnh lên và dịch ngay nội dung chữ trong ảnh.',
    emoji: '🌐',
    category: 'image',
    qCost: 2,
    isNew: true,
  },
  {
    slug: 'ocr',
    htmlFile: 'ocr.html',
    name: 'OCR',
    nameVi: 'Nhận dạng chữ (OCR)',
    description: 'Extract text from images using optical character recognition.',
    descVi: 'Trích xuất chữ từ ảnh bằng công nghệ nhận dạng ký tự quang học.',
    emoji: '🔍',
    category: 'image',
    qCost: 2,
    isNew: true,
  },
  {
    slug: 'image-to-pdf',
    htmlFile: 'image-to-pdf.html',
    name: 'Image to PDF',
    nameVi: 'Ảnh sang PDF',
    description: 'Convert one or multiple images to a PDF file.',
    descVi: 'Chuyển một hoặc nhiều ảnh thành file PDF.',
    emoji: '📑',
    category: 'image',
    qCost: 1,
  },

  // ── PDF ───────────────────────────────────────────────────────
  {
    slug: 'pdf-tool',
    htmlFile: 'pdf-tool.html',
    name: 'PDF Tool',
    nameVi: 'Công cụ PDF',
    description: 'Merge, split, rotate and compress PDF files.',
    descVi: 'Gộp, tách, xoay và nén file PDF toàn diện.',
    emoji: '📄',
    category: 'pdf',
    qCost: 1,
  },
  {
    slug: 'pdf-to-word',
    htmlFile: 'pdf-to-word.html',
    name: 'PDF to Word',
    nameVi: 'PDF sang Word',
    description: 'Convert PDF to editable .docx with preserved formatting.',
    descVi: 'Chuyển PDF sang Word (.docx) — giữ nguyên bảng biểu, font, layout.',
    emoji: '📝',
    category: 'pdf',
    qCost: 2,
  },
  {
    slug: 'pdf-reader',
    htmlFile: 'pdf-reader.html',
    name: 'PDF Reader',
    nameVi: 'Đọc PDF',
    description: 'Read and annotate PDF files in your browser.',
    descVi: 'Đọc và ghi chú PDF ngay trên trình duyệt.',
    emoji: '📖',
    category: 'pdf',
    qCost: 1,
  },

  // ── TEXT ──────────────────────────────────────────────────────
  {
    slug: 'word-counter',
    htmlFile: 'word-counter.html',
    name: 'Word Counter',
    nameVi: 'Đếm từ',
    description: 'Count words, characters, sentences and reading time.',
    descVi: 'Đếm từ, ký tự, câu và thời gian đọc ước tính.',
    emoji: '🔢',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'markdown-editor',
    htmlFile: 'markdown-editor.html',
    name: 'Markdown Editor',
    nameVi: 'Markdown Editor',
    description: 'Write Markdown with live preview and export options.',
    descVi: 'Viết Markdown với xem trước trực tiếp và xuất HTML/PDF.',
    emoji: '✍️',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'text-diff',
    htmlFile: 'text-diff.html',
    name: 'Text Diff',
    nameVi: 'So sánh văn bản',
    description: 'Compare two texts and highlight differences.',
    descVi: 'So sánh hai đoạn văn bản và làm nổi bật điểm khác biệt.',
    emoji: '🔀',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'lorem-ipsum',
    htmlFile: 'lorem-ipsum.html',
    name: 'Lorem Ipsum',
    nameVi: 'Lorem Ipsum',
    description: 'Generate placeholder text in multiple languages and formats.',
    descVi: 'Tạo văn bản giả cho design — đa ngôn ngữ, nhiều định dạng.',
    emoji: '📃',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'readability',
    htmlFile: 'readability.html',
    name: 'Readability Checker',
    nameVi: 'Kiểm tra độ dễ đọc',
    description: 'Check how readable your text is with Flesch score and suggestions.',
    descVi: 'Kiểm tra độ dễ đọc của văn bản, phân tích câu dài, từ phức tạp.',
    emoji: '📚',
    category: 'text',
    qCost: 0,
  },
  {
    slug: 'notes',
    htmlFile: 'notes.html',
    name: 'Notes',
    nameVi: 'Ghi chú',
    description: 'Quick notes that sync across your sessions.',
    descVi: 'Ghi chú nhanh, lưu trữ trên thiết bị của bạn.',
    emoji: '📓',
    category: 'text',
    qCost: 0,
  },

  // ── DEV ───────────────────────────────────────────────────────
  {
    slug: 'json-formatter',
    htmlFile: 'json-formatter.html',
    name: 'JSON Formatter',
    nameVi: 'Định dạng JSON',
    description: 'Format, validate and minify JSON with syntax highlighting.',
    descVi: 'Format, kiểm tra và minify JSON với syntax highlighting.',
    emoji: '{ }',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'regex-tester',
    htmlFile: 'regex-tester.html',
    name: 'Regex Tester',
    nameVi: 'Kiểm tra Regex',
    description: 'Test regular expressions with real-time match highlighting.',
    descVi: 'Kiểm tra regex với highlight kết quả khớp theo thời gian thực.',
    emoji: '.*',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'hash-generator',
    htmlFile: 'hash-generator.html',
    name: 'Hash Generator',
    nameVi: 'Tạo mã Hash',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-512 hashes from text or files.',
    descVi: 'Tạo mã hash MD5, SHA-1, SHA-256, SHA-512 từ văn bản hoặc file.',
    emoji: '#️⃣',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'encode-tools',
    htmlFile: 'encode-tools.html',
    name: 'Encode Tools',
    nameVi: 'Mã hóa & Giải mã',
    description: 'Encode and decode Base64, URL, HTML entities and more.',
    descVi: 'Mã hóa và giải mã Base64, URL, HTML entities và nhiều hơn.',
    emoji: '🔤',
    category: 'dev',
    qCost: 0,
  },
  {
    slug: 'api-tester',
    htmlFile: 'api-tester.html',
    name: 'API Tester',
    nameVi: 'Kiểm tra API',
    description: 'Send HTTP requests and inspect responses — like a mini Postman.',
    descVi: 'Gửi HTTP request và xem response — như Postman mini trên browser.',
    emoji: '🔌',
    category: 'dev',
    qCost: 1,
  },
  {
    slug: 'ip-lookup',
    htmlFile: 'ip-lookup.html',
    name: 'IP & DNS Lookup',
    nameVi: 'Tra cứu IP & DNS',
    description: 'Look up IP info, geolocation, ISP and DNS records.',
    descVi: 'Tra cứu thông tin IP, vị trí, ISP và DNS records của bất kỳ domain.',
    emoji: '🌐',
    category: 'dev',
    qCost: 0,
  },

  // ── CONVERT ───────────────────────────────────────────────────
  {
    slug: 'converter',
    htmlFile: 'converter.html',
    name: 'Unit Converter',
    nameVi: 'Chuyển đổi đơn vị',
    description: 'Convert between units — length, weight, temperature, area and more.',
    descVi: 'Chuyển đổi đơn vị — độ dài, khối lượng, nhiệt độ, diện tích.',
    emoji: '⚖️',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'unit-converter',
    htmlFile: 'unit-converter.html',
    name: 'Unit Converter Pro',
    nameVi: 'Chuyển đổi đơn vị Pro',
    description: 'Advanced unit conversion with more categories.',
    descVi: 'Chuyển đổi đơn vị nâng cao với nhiều danh mục hơn.',
    emoji: '📐',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'currency',
    htmlFile: 'currency.html',
    name: 'Currency Converter',
    nameVi: 'Đổi tiền tệ',
    description: 'Real-time currency conversion with 18+ currencies.',
    descVi: 'Chuyển đổi tiền tệ theo tỷ giá realtime — hỗ trợ 18+ loại tiền.',
    emoji: '💱',
    category: 'convert',
    qCost: 0,
  },
  {
    slug: 'qr-generator',
    htmlFile: 'qr-generator.html',
    name: 'QR Generator',
    nameVi: 'Tạo mã QR',
    description: 'Generate QR codes for URLs, text, and WiFi credentials.',
    descVi: 'Tạo mã QR cho link, văn bản và WiFi — tải về PNG miễn phí.',
    emoji: '⬛',
    category: 'convert',
    qCost: 0,
  },

  // ── PRIVACY ───────────────────────────────────────────────────
  {
    slug: 'password-generator',
    htmlFile: 'password-generator.html',
    name: 'Password Generator',
    nameVi: 'Tạo mật khẩu',
    description: 'Generate strong, customizable passwords instantly.',
    descVi: 'Tạo mật khẩu mạnh theo yêu cầu — độ dài, ký tự đặc biệt.',
    emoji: '🔑',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'secure-notes',
    htmlFile: 'secure-notes.html',
    name: 'Secure Notes',
    nameVi: 'Ghi chú bảo mật',
    description: 'Encrypted notes that never leave your device.',
    descVi: 'Ghi chú mã hóa AES — không bao giờ rời khỏi thiết bị của bạn.',
    emoji: '🔐',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'vault',
    htmlFile: 'vault.html',
    name: 'Vault',
    nameVi: 'Két bảo mật',
    description: 'Encrypted local storage for sensitive data.',
    descVi: 'Lưu trữ dữ liệu nhạy cảm với mã hóa cục bộ.',
    emoji: '🏦',
    category: 'privacy',
    qCost: 0,
  },
  {
    slug: 'file-vault',
    htmlFile: 'file-vault.html',
    name: 'File Vault',
    nameVi: 'Két file',
    description: 'Encrypt and store files securely in your browser.',
    descVi: 'Mã hóa và lưu trữ file bảo mật ngay trên trình duyệt.',
    emoji: '🔒',
    category: 'privacy',
    qCost: 1,
  },
  {
    slug: 'temp-email',
    htmlFile: 'temp-email.html',
    name: 'Temp Email',
    nameVi: 'Email tạm thời',
    description: 'Generate a temporary disposable email address.',
    descVi: 'Tạo địa chỉ email tạm thời để tránh spam.',
    emoji: '📧',
    category: 'privacy',
    qCost: 0,
  },

  // ── MEDIA ─────────────────────────────────────────────────────
  {
    slug: 'audio-recorder',
    htmlFile: 'audio-recorder.html',
    name: 'Audio Recorder',
    nameVi: 'Ghi âm',
    description: 'Record audio from your microphone and download as MP3/WAV.',
    descVi: 'Ghi âm từ microphone và tải xuống MP3/WAV.',
    emoji: '🎙️',
    category: 'media',
    qCost: 1,
  },
  {
    slug: 'screen-recorder',
    htmlFile: 'screen-recorder.html',
    name: 'Screen Recorder',
    nameVi: 'Quay màn hình',
    description: 'Record your screen directly in the browser.',
    descVi: 'Quay màn hình trực tiếp trên trình duyệt, không cần cài phần mềm.',
    emoji: '🎬',
    category: 'media',
    qCost: 1,
  },

  // ── UTILITY ───────────────────────────────────────────────────
  {
    slug: 'pomodoro',
    htmlFile: 'pomodoro.html',
    name: 'Pomodoro Timer',
    nameVi: 'Đồng hồ Pomodoro',
    description: 'Focus timer using the Pomodoro technique.',
    descVi: 'Hẹn giờ tập trung theo kỹ thuật Pomodoro — làm việc hiệu quả hơn.',
    emoji: '🍅',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'world-clock',
    htmlFile: 'world-clock.html',
    name: 'World Clock',
    nameVi: 'Đồng hồ thế giới',
    description: 'See current time in cities around the world.',
    descVi: 'Xem giờ hiện tại tại các thành phố trên thế giới.',
    emoji: '🌍',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'random',
    htmlFile: 'random.html',
    name: 'Random Generator',
    nameVi: 'Tạo số ngẫu nhiên',
    description: 'Generate random numbers, shuffle lists, flip coins.',
    descVi: 'Tạo số ngẫu nhiên, xáo trộn danh sách, tung đồng xu.',
    emoji: '🎲',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'typing_trainer_10_fingers',
    htmlFile: 'typing_trainer_10_fingers.html',
    name: 'Typing Trainer',
    nameVi: 'Luyện gõ 10 ngón',
    description: 'Practice touch typing with 10 fingers — improve your WPM.',
    descVi: 'Luyện gõ phím 10 ngón chuyên nghiệp — tăng tốc độ gõ.',
    emoji: '⌨️',
    category: 'utility',
    qCost: 0,
  },
  {
    slug: 'cv-builder',
    htmlFile: 'cv-builder.html',
    name: 'CV Builder',
    nameVi: 'Tạo CV',
    description: 'Build a professional CV and export to PDF.',
    descVi: 'Tạo CV chuyên nghiệp và xuất file PDF.',
    emoji: '💼',
    category: 'utility',
    qCost: 2,
  },
  {
    slug: 'diary',
    htmlFile: 'diary.html',
    name: 'Diary',
    nameVi: 'Nhật ký',
    description: 'Private diary with local encrypted storage.',
    descVi: 'Nhật ký cá nhân — lưu trữ mã hóa trên thiết bị của bạn.',
    emoji: '📔',
    category: 'utility',
    qCost: 1,
  },
  {
    slug: 'flashcards',
    htmlFile: 'flashcards.html',
    name: 'Flashcards',
    nameVi: 'Thẻ ghi nhớ',
    description: 'Create and study flashcard decks with spaced repetition.',
    descVi: 'Tạo và học thẻ ghi nhớ với kỹ thuật lặp lại ngắt quãng.',
    emoji: '🃏',
    category: 'utility',
    qCost: 1,
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS.find(t => t.slug === slug);
}

export function getFreeTools(): Tool[] {
  return TOOLS.filter(t => t.qCost === 0);
}

export function getPaidTools(): Tool[] {
  return TOOLS.filter(t => t.qCost > 0);
}
{
  slug: 'word-to-pdf',
  htmlFile: 'word-to-pdf.html',
  name: 'Word to PDF',
  nameVi: 'Word sang PDF',
  description: 'Convert .docx to PDF in your browser. No upload, no account.',
  descVi: 'Chuyển .docx sang PDF ngay trên trình duyệt. Không upload, không cần tài khoản.',
  emoji: '📄',
  category: 'pdf',
  qCost: 0,
},